export const START_FETCHING = 'START_FETCHING';
export const END_FETCHING = 'END_FETCHING';
export const OPEN_RESTORE_PASSWORD = 'OPEN_RESTORE_PASSWORD';
export const CLOSE_RESTORE_PASSWORD = 'CLOSE_RESTORE_PASSWORD';
export const SET_SORT_CONFIG = 'SET_SORT_CONFIG';
